---
- name: Configure Analytics Dashboard Server
  hosts: all
  become: true
  vars:
    app_name: "analytics-dashboard"
    app_dir: "/opt/{{ app_name }}"
    docker_compose_version: "2.20.0"
    node_version: "18.x"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Copy environment file
      template:
        src: templates/.env.j2
        dest: "{{ app_dir }}/.env"
        mode: '0600'

    - name: Start Docker services
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        restarted: yes 